# Generated by Django 5.2.1 on 2025-05-15 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En curso'), ('finish', 'Finalizado')], default='pending', max_length=11)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('players', models.PositiveIntegerField()),
                ('prize', models.PositiveIntegerField(help_text='Premio')),
            ],
        ),
    ]
