# Generated by Django 5.2.1 on 2025-05-15 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_tournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='mode',
            field=models.CharField(choices=[('bullet', 'Bullet'), ('standard', 'Standard')], default='bullet', max_length=20),
            preserve_default=False,
        ),
    ]
